# docker-compose.yml
version: '3.8'

services:
  travel-planner:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./output:/app/output
    command: python travel_planner.py --destination "Georgia" --budget 1500 --days 7

